### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by Lusindiso** [Lusindiso/space-travelers-hub#25]
https://github.com/Lusindiso/space-travelers-hub/projects/1
We are 2 people in this project.

**Comment by AshakaE** [comment]
Hi @Lusindiso , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lusindiso** [comment]
@AshakaE 
Thank you for reviewing our project.
